services:

  app:
    build:
      context: packages/backend
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/shortener?authSource=admin
    ports: 
      - "3030:3030"
    depends_on:
      mongo:
        condition: service_healthy
        
  mongo:
    image: mongo:7.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.stats()", "-u", "root", "-p", "example", "mongodb://localhost:27017/shortener?authSource=admin"]
      interval: 5s
      timeout: 30s
      retries: 3
